apiVersion: 1
dataDisplay:
  noneValues:
  - none
  - unknown
  - null
  - NA
  sectionSep1: ', '
  sectionSep2: ', Ln. '
  textFormats:
    word#layout-orig-full:
      method: layoutOrigFull
    word#layout-orig-lite:
      method: layoutOrigLite
    word#layout-trans-full:
      method: layoutTransFull
    word#layout-trans-fuzzy:
      method: layoutTransFuzzy
    word#layout-trans-lite:
      method: layoutTransLite
docs:
  charText: NENA transcription script
  charUrl: '{docBase}/transcription{docExt}'
  docPage: features.md
  featureBase: '{docBase}/features{docExt}#<feature>'
  featurePage: ''
provenanceSpec:
  corpus: Northeastern Neo-Aramaic Text Corpus
  doi: 10.5281/zenodo.3250721
  org: CambridgeSemiticsLab
  repo: nena_tf
  version: '0.02'
  webBase: '{urlGh}/{org}/nena_corpus/blob/master/nena'
  webHint: Show this title in the NENA repository
  webUrl: '{version}/<1>/<2>.nena'
typeDisplay:
  dialect:
    label: '{dialect}'
  inton:
    wrap: false
  line:
    condense: true
    label: '{number}'
  paragraph:
    label: '{number}'
  stress:
    base: true
    wrap: false
  text:
    label: '{text_id}'
    features: title place
    featuresBare: informant
  word:
    features: gloss
    featuresBare: lemma
    wrap: false
  subsentence:
    chunkOf: sentence
    children:
      - inton
      - stress
writing: cld
