apiVersion: 1
dataDisplay:
  noneValues:
  - none
  - unknown
  - null
  - NA
  sectionSep1: ', '
  sectionSep2: ', Ln. '
  textFormats:
    layout-orig-full: layoutOrigFull
    layout-orig-lite: word#layoutOrigLite
    layout-trans-full: word#layoutTransFull
    layout-trans-fuzzy: word#layoutTransFuzzy
    layout-trans-lite: word#layoutTransLite
docs:
  charText: NENA transcription script
  charUrl: '{docBase}/transcription{docExt}'
  docPage: features.md
  featureBase: '{docBase}/features{docExt}#<feature>'
  featurePage: ''
  webBase: '{urlGh}/{org}/nena_corpus/blob/master/nena'
  webHint: Show this title in the NENA repository
  webUrl: '{version}/<1>/<2>.nena'
interfaceDefaults:
  showFeatures: false
provenanceSpec:
  corpus: Northeastern Neo-Aramaic Text Corpus
  doi: 10.5281/zenodo.3250721
  org: CambridgeSemiticsLab
  repo: nena_tf
  version: '0.02'
typeDisplay:
  inton:
    wrap: false
  line:
    children: paragraph
  paragraph:
    children: sentence
    label: '{number}'
  sentence:
    children: inton
    condense: true
  stress:
    base: true
    wrap: false
  subsentence:
    children: inton
  text:
    features: title place
    featuresBare: informant
  word:
    features: gloss
    featuresBare: gloss
    wrap: false
writing: cld
